slogan: "wubba lubba dub dub."

show_heart: true

show_slogan: true

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    # icon: "fa fa-user"
  - title: RSS
    url: atom.xml
    intro: "Subscribe me."
    # icon: "fa fa-user"

links:
  - title: hexo-theme-bithack
    url: https://github.com/Ares-X/hexo-theme-freemind.bithack
    intro: ""
    icon: false

  # - title: "My LinkedIn"
  #   url: http://www.linkedin.com/in/xxx
  #   intro: "My Linkin account."
  #   icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts
- links

rss: atom.xml
fancybox: true
favicon: favicon.png
#duoshuo_shortname: 


# Analytics
google_analytics:
  enable: true
  siteid: UA-70812759-1


# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR

#valine
valine: 
  enable: false
  appId: 'xxx'
  appKey: 'xxx'
  placeholder: ""
  visitor: false
  avatar: 'monsterid'
  requiredFields: ['nick','mail']
  pageView: false
  
#waline
waline:
  enable: false
  serverURL: ''
  pageview: false
  lang: en
  dark: true
  requiredMeta: ['nick', 'mail']
  locale:
    placeholder: 'Comment with Email address will get notification when replied'

# the Gitalk config，default disabled # Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: true #默认的是false，没有打开
  owner: 'fineday009'
  repo: 'fineday009.github.io.comments'
  oauth:
    clientId: '61aa04ff5aef6133e5a0'
    clientSecret: 'b81fb271bb03c7b1e63408537ce5a7e870cdecd5'
  admin: ['fineday009']